# Use the centos 7 base image

# Add your maintainer info

# Create a user named duffman

# Install epel-release and mosquitto (epel-release must be installed first)

# Create the colors directory from colors.tar

# Move skeeter.sh over to /skeeter.sh

# Make skeeter.sh executable

# Allow connections to port 1883

# Switch to the duffman user

# Run the skeeter.sh script
