# Edit this file to create an nginx webserver
# Pull from centos:8

# Install nginx

# Publish port 80 to the outside world

# Copy index.html and duffman.png into /usr/share/nginx/html directory

# Run the command 'nginx -g daemon off;'
